[tox]
min_version = 4

requires =
    virtualenv
    pluggy

envlist = type pytest

[testenv]
deps=pytest
allowlist_externals = pytest
commands =
    pytest tests {posargs}
passenv =
    HOME

[pytest]
minversion = 6.0
addopts = -ra -q --import-mode=importlib
testpaths =  tests
pythonpath = . src


[testenv:type]
deps = mypy
commands = mypy src
